Testing Kalman Filter implementation tracking an obejects position and velocity over time

In [2]:
import unittest
import numpy as np
#import pytest
#import ipytest
#ipytest.autoconfig()
#https://docs.python.org/3/library/unittest.html

from Kalman_Filter import KalmanFilter

Resources:
- https://www2.isye.gatech.edu/~yxie77/ece587/Lecture17.pdf
-- This illustrates that Differental entropy representian a value 

In [5]:
#kf = KalmanFilter(initial_x=0.4, initial_v=0.7)
#print(kf.x)

class TestStringKalmanFilter(unittest.TestCase):

    def test_contructor_with_x_and_v(self):
        x = 0.4
        v = 0.7
        kf = KalmanFilter(initial_x=x, initial_v=v, accel_variance=1.2)
        self.assertAlmostEqual(kf.position, x)
        self.assertAlmostEqual(kf.velocity, v)
        print("Passed")
    
    def test_predit_functionality(self):
        x = 0.4
        v = 0.7
        kf = KalmanFilter(initial_x=x, initial_v=v, accel_variance=1.2)
        kf.predict(0.1)   # dt = 0.1
        # Test if the matrix dimensions (shape) is consistent after running the predict step
        self.assertEqual(kf.mean_state_variable.shape, (2, )) # vector only has 1 dimension as a 2x1
        self.assertEqual(kf.covariance_matrix.shape, (2, 2)) 

        print("Predict - Correct Matrix Dimensions - PASSED")

    
    def test_predit_increase_state_estimation_uncertainty(self):
        """
        By integrating over time, the more we call predict, the uncertainty state estimate should reflected in the covariance matrix
        """
        x = 0.4
        v = 0.7
        kf = KalmanFilter(initial_x=x, initial_v=v, accel_variance=1.2)
        
        # calling predict multiple times
        for time_step in range(10):
            # the differnatial entropy of a gaussian random variable is represented as determinant of the Covariance matrix
            # since in this case the covariance matrix is the identity then the det(Cov_Matrix) = product of variance of each dimension
            # aka variance of position * variance of speed
            determinant_before = np.linalg.det(kf.covariance_matrix)
            kf.predict(0.1)   # dt = 0.1 -- time step of 0.1 seconds
            determinant_after = np.linalg.det(kf.covariance_matrix)
            self.assertGreater(determinant_after, determinant_before)
            print(determinant_before, determinant_after)

        
        # Test if the matrix dimensions (shape) is consistent after running the predict step
        self.assertEqual(kf.mean_state_variable.shape, (2, )) # vector only has 1 dimension as a 2x1
        self.assertEqual(kf.covariance_matrix.shape, (2, 2)) 
            
        print("Predict - Over multiple prediction steps (time) -  Passed")
    
        

if __name__ == '__main__':
    unittest.main(argv=[''], exit=False)

...
----------------------------------------------------------------------
Ran 3 tests in 0.070s

OK


Passed
[[1.  0.1]
 [0.  1. ]]
[0.47 0.7 ]
Predict - Correct Matrix Dimensions - PASSED
[[1.  0.1]
 [0.  1. ]]
[0.47 0.7 ]
1.0 1.01203
[[1.  0.1]
 [0.  1. ]]
[0.54 0.7 ]
1.01203 1.02430144
[[1.  0.1]
 [0.  1. ]]
[0.61 0.7 ]
1.02430144 1.0370586400000001
[[1.  0.1]
 [0.  1. ]]
[0.68 0.7 ]
1.0370586400000001 1.0505488
[[1.  0.1]
 [0.  1. ]]
[0.75 0.7 ]
1.0505488 1.0650220000000001
[[1.  0.1]
 [0.  1. ]]
[0.82 0.7 ]
1.0650220000000001 1.0807312000000002
[[1.  0.1]
 [0.  1. ]]
[0.89 0.7 ]
1.0807312000000002 1.09793224
[[1.  0.1]
 [0.  1. ]]
[0.96 0.7 ]
1.09793224 1.1168838399999996
[[1.  0.1]
 [0.  1. ]]
[1.03 0.7 ]
1.1168838399999996 1.1378475999999995
[[1.  0.1]
 [0.  1. ]]
[1.1 0.7]
1.1378475999999995 1.161088
Predict - Over multiple prediction steps (time) -  Passed
